### ISSUE TITLE
Your first AWS CDK app guide destroy instructions don't delete the S3 bucket

### ISSUE THREAD

**Issue by tkgregory** [awsdocs/aws-cdk-guide#285] opened 2020-11-13 11:16 UTC
At the end of the *Your first AWS CDK app guide* guide it details adding `removalPolicy: cdk.RemovalPolicy.DESTROY` to your S3 Bucket definition.

Once you've made this file change `npm run build && cdk diff` correctly identifies the change. 
```
tom@DESKTOP-J0R9V8A:/mnt/c/workspace/hello-cdk$ npm run build && cdk diff

> hello-cdk@0.1.0 build /mnt/c/workspace/hello-cdk
> tsc

Stack HelloCdkStack
Resources
[~] AWS::S3::Bucket MyFirstBucket MyFirstBucketB8884501
 ├─ [~] DeletionPolicy
 │   ├─ [-] Retain
 │   └─ [+] Delete
 └─ [~] UpdateReplacePolicy
     ├─ [-] Retain
     └─ [+] Delete
```
However, when you run `npm run build && cdk deploy` the change does not get deployed to the CloudFormation stack.

```
tom@DESKTOP-J0R9V8A:/mnt/c/workspace/hello-cdk$ npm run build && cdk deploy

> hello-cdk@0.1.0 build /mnt/c/workspace/hello-cdk
> tsc

HelloCdkStack: deploying...
HelloCdkStack: creating CloudFormation changeset...

 ✅  HelloCdkStack (no changes)

Stack ARN:
arn:aws:cloudformation:eu-west-1:299404798587:stack/HelloCdkStack/a4db22d0-259d-11eb-ad9c-06bb93b52142
```
Here's the definition according to the CloudFormation stack in AWS Console i.e. no change

```
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```

Interestingly, when I run `npm run build && cdk synth` the `DeletionPolicy` looks correct:

```
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
```

The expectation here is that my stack's `DeletionPolicy` is updated. This would mean when I run `cdk destroy` as described in the guide the bucket would be deleted. 

> cdk destroy
> Enter y to approve the changes and delete any stack resources.
> This wouldn't have worked if we hadn't changed the bucket's RemovalPolicy just a minute ago!

Right now I have to manually go and delete the bucket.

I'm not sure if this is a CDK bug, but these things are very confusing for a first-time user so please update the docs accordingly.

I'm using CDK version `1.73.0 (build eb6f3a9)` with Typescript.

**Comment by Jerry-AWS** [comment] 2020-11-14 03:59
This should work. I'll have a look and see if I can duplicate this issue.

**Comment by Jerry-AWS** [comment] 2020-11-17 19:07
@tkgregory I've filed a bug related to this in the CDK repo. https://github.com/aws/aws-cdk/issues/11521

I think this is the root cause of your issue here.

**Comment by Jerry-AWS** [comment] 2020-11-18 15:52
That said, I'm updating the Getting Started topic to work around this issue.

**Comment by Jerry-AWS** [comment] 2020-11-18 17:16
@tkgregory I've updated the "Your First App" topic and it should now update the removal policy as intended. This change should go live on docs.aws.amazon.com in the next 24 hours. As an added benefit, the topic now shows an example of an IAM policy diff, which is a nice thing to show off in an introductory tutorial, so win-win.  :-)

I'm going to close this, but feel free to re-open it if you spot any problems with the updated tutorial. Thanks again for finding and reporting this issue.

**Closed by Jerry-AWS** 2020-11-18 17:16 UTC
