### ISSUE TITLE
cdk_pipeline.md

### ISSUE THREAD

**Issue by smaud** [awsdocs/aws-cdk-guide#289] opened 2020-12-18 07:44 UTC
the cdk_pipeline.md doco doesn't create a CodeDeploy blue/green deployment, but only uses in-place deployment with cloudformation. 

Please check that the code example works and provide a repository which we can fork to test.

**Comment by ccfife** [comment] 2020-12-18 19:48
The issue is that there is a line missing in the code; instead of 

const func = new lambda.Function(this, 'Lambda', {
  code: this.lambdaCode,
  handler: 'index.main',
  runtime: lambda.Runtime.NODEJS_10_X,
});
it should be:

const func = new lambda.Function(this, 'Lambda', {
  code: this.lambdaCode,
  handler: 'index.main',
  runtime: lambda.Runtime.NODEJS_10_X,
  description: `Function generated on: ${new Date().toISOString()}`,
});

**Comment by sholtomaud** [comment] 2020-12-19 05:42
Do you have a repo for this, and how do we test it to make sure it works?

**Comment by smaud** [comment] 2020-12-20 01:40
@ccfife I've just tested this code and it didn't deploy a blue/green with CodeDeployDefault.LambdaLinear10PercentEvery1Minute it just did a Cloudformation in-place deployment. 

I'd like to suggest that you create a repo with your code and have some tests to verify that it actually works according to the concept of operations.

**Comment by smaud** [comment] 2020-12-20 01:50
If we manually add an appspec to the deployment group then the codedeploy will trigger a CodeDeployDefault.LambdaLinear10PercentEvery1Minute  deployment. But how do we add this appspec in the CDK?

```
version: 0.0
 Resources:
 - myLambdaFunction:
 Type: AWS::Lambda::Function
 Properties:
 Name: "LambdaDeploymentStack"
 Alias: "Dev1608265829647"
 CurrentVersion: "2"
 TargetVersion: "3"
```

**Comment by smaud** [comment] 2020-12-20 02:49
I can confirm that the following repo works. I suggest the doco is updated accordingly with a link to this repo:

https://github.com/skinny85/cdk-guide-codepipeline-example

**Comment by Jerry-AWS** [comment] 2021-02-17 00:14
This should be fixed thanks to @skinny85's work.

**Closed by Jerry-AWS** 2021-02-17 00:14 UTC
